---
version: '3.1'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: graph
      POSTGRES_USER: graph
      POSTGRES_PASSWORD: graph
    ports:
      - "5432:5432"
