---

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        integration.: WARN
    zone: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL
  h2:
    console:
      enabled: false
      path: /console
  main:
    banner-mode: "off"